name: publish website
on:
  push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
       with:
         fetch-depth: 0
         fetch-tags: true
     - name: Install dependencies
       run: |
         python -m venv virtualenv
         source virtualenv/bin/activate
         python -m pip install -r requirements.txt
     - name: make website
       run: |
         source virtualenv/bin/activate
         make freeze
     - name: Deploy
       if: github.ref == 'refs/heads/main'
       uses: peaceiris/actions-gh-pages@v4
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: ./build
